before_install:
	- sudo apt-get -qq update
	- sudo apt-get install -y pdf2svg
#before_script:
# are these available with language:python? > no!  see v0.4.15
#- phantomjs --version
#- casperjs --version
env:
- TOXENV=py27
install: pip install -U tox
language: python
python: 2.7
script: tox -e ${TOXENV}
#after_failure: "cat /home/travis/build/jsaponara/opentaxforms/.tox/log/tox-0.log"
