# are these available with language:python? > no!  see v0.4.15
#- phantomjs --version
#- casperjs --version
language: python
python:
  - '2.7'
  - '3.5'
install:
    - sudo apt-get -qq update
    - sudo apt-get install -y pdf2svg
    - pip install tox
script: tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
